"""Add trips bookings payments reviews (uppercase 2)

Revision ID: 0d2ac947a3d8
Revises: a0dd10e2b56c
Create Date: 2026-08-23 19:57:31.340822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2ac947a3d8'
down_revision: Union[str, Sequence[str], None] = 'a0dd10e2b56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
