"""Add trips domain

Revision ID: 1c32831cfb11
Revises: beb542642525
Create Date: 2026-08-22 20:13:15.941670

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1c32831cfb11"
down_revision: str | Sequence[str] | None = "beb542642525"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
