"""Add Listings

Revision ID: 5a9dc333299a
Revises: a9e969275740
Create Date: 2026-08-22 19:46:26.124407

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a9dc333299a"
down_revision: str | Sequence[str] | None = "a9e969275740"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amenities",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_amenities_id"), "amenities", ["id"], unique=False)
    op.create_index(op.f("ix_amenities_name"), "amenities", ["name"], unique=True)
    op.create_table(
        "listings",
        sa.Column("host_id", sa.Uuid(), nullable=False),
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "property_type",
            sa.Enum(
                "HOTEL",
                "HOSTEL",
                "HOMESTAY",
                "APARTMENT",
                "VILLA",
                "CAMP",
                "MONASTERY",
                "ASHRAM",
                "RESORT",
                "CO_LIVING",
                "UNIQUE_STAY",
                name="property_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("guest_capacity", sa.Integer(), nullable=False),
        sa.Column("bedrooms", sa.Integer(), nullable=False),
        sa.Column("beds", sa.Integer(), nullable=False),
        sa.Column("bathrooms", sa.Float(), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "UNLISTED", name="listing_status_enum"),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum("PENDING", "VERIFIED", "REJECTED", name="verification_status_enum"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"], ["destinations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["host_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listings_destination_id"), "listings", ["destination_id"], unique=False
    )
    op.create_index(op.f("ix_listings_host_id"), "listings", ["host_id"], unique=False)
    op.create_index(op.f("ix_listings_id"), "listings", ["id"], unique=False)
    op.create_index(
        op.f("ix_listings_property_type"), "listings", ["property_type"], unique=False
    )
    op.create_index(op.f("ix_listings_slug"), "listings", ["slug"], unique=True)
    op.create_index(op.f("ix_listings_status"), "listings", ["status"], unique=False)
    op.create_table(
        "listing_amenities",
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("amenity_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["amenity_id"], ["amenities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("listing_id", "amenity_id", name="uq_listing_amenity"),
    )
    op.create_index(
        op.f("ix_listing_amenities_amenity_id"),
        "listing_amenities",
        ["amenity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listing_amenities_id"), "listing_amenities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_listing_amenities_listing_id"),
        "listing_amenities",
        ["listing_id"],
        unique=False,
    )
    op.create_table(
        "listing_availabilities",
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("listing_id", "date", name="uq_listing_date"),
    )
    op.create_index(
        op.f("ix_listing_availabilities_date"),
        "listing_availabilities",
        ["date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listing_availabilities_id"),
        "listing_availabilities",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listing_availabilities_is_available"),
        "listing_availabilities",
        ["is_available"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listing_availabilities_listing_id"),
        "listing_availabilities",
        ["listing_id"],
        unique=False,
    )
    op.create_table(
        "listing_images",
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listing_images_id"), "listing_images", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_listing_images_listing_id"),
        "listing_images",
        ["listing_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listing_images_listing_id"), table_name="listing_images")
    op.drop_index(op.f("ix_listing_images_id"), table_name="listing_images")
    op.drop_table("listing_images")
    op.drop_index(
        op.f("ix_listing_availabilities_listing_id"),
        table_name="listing_availabilities",
    )
    op.drop_index(
        op.f("ix_listing_availabilities_is_available"),
        table_name="listing_availabilities",
    )
    op.drop_index(
        op.f("ix_listing_availabilities_id"), table_name="listing_availabilities"
    )
    op.drop_index(
        op.f("ix_listing_availabilities_date"), table_name="listing_availabilities"
    )
    op.drop_table("listing_availabilities")
    op.drop_index(
        op.f("ix_listing_amenities_listing_id"), table_name="listing_amenities"
    )
    op.drop_index(op.f("ix_listing_amenities_id"), table_name="listing_amenities")
    op.drop_index(
        op.f("ix_listing_amenities_amenity_id"), table_name="listing_amenities"
    )
    op.drop_table("listing_amenities")
    op.drop_index(op.f("ix_listings_status"), table_name="listings")
    op.drop_index(op.f("ix_listings_slug"), table_name="listings")
    op.drop_index(op.f("ix_listings_property_type"), table_name="listings")
    op.drop_index(op.f("ix_listings_id"), table_name="listings")
    op.drop_index(op.f("ix_listings_host_id"), table_name="listings")
    op.drop_index(op.f("ix_listings_destination_id"), table_name="listings")
    op.drop_table("listings")
    op.drop_index(op.f("ix_amenities_name"), table_name="amenities")
    op.drop_index(op.f("ix_amenities_id"), table_name="amenities")
    op.drop_table("amenities")
    # ### end Alembic commands ###
