"""Add Destination model

Revision ID: a9e969275740
Revises: 86a65d01a122
Create Date: 2026-08-22 19:39:01.672897

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9e969275740"
down_revision: str | Sequence[str] | None = "86a65d01a122"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destinations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("state_province_region", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.String(length=500), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("hero_image_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_destinations_country"), "destinations", ["country"], unique=False
    )
    op.create_index(op.f("ix_destinations_id"), "destinations", ["id"], unique=False)
    op.create_index(
        op.f("ix_destinations_is_active"), "destinations", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_destinations_name"), "destinations", ["name"], unique=False
    )
    op.create_index(op.f("ix_destinations_slug"), "destinations", ["slug"], unique=True)
    op.create_index(
        op.f("ix_destinations_state_province_region"),
        "destinations",
        ["state_province_region"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_destinations_state_province_region"), table_name="destinations"
    )
    op.drop_index(op.f("ix_destinations_slug"), table_name="destinations")
    op.drop_index(op.f("ix_destinations_name"), table_name="destinations")
    op.drop_index(op.f("ix_destinations_is_active"), table_name="destinations")
    op.drop_index(op.f("ix_destinations_id"), table_name="destinations")
    op.drop_index(op.f("ix_destinations_country"), table_name="destinations")
    op.drop_table("destinations")
    # ### end Alembic commands ###
