"""Add experiences domain

Revision ID: beb542642525
Revises: 5a9dc333299a
Create Date: 2026-08-22 20:00:52.170731

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "beb542642525"
down_revision: str | Sequence[str] | None = "5a9dc333299a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experience_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experience_categories_id"),
        "experience_categories",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experience_categories_name"),
        "experience_categories",
        ["name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_experience_categories_slug"),
        "experience_categories",
        ["slug"],
        unique=True,
    )
    op.create_table(
        "experiences",
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("guest_capacity", sa.Integer(), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("meeting_point", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "PUBLISHED", "UNLISTED", name="experience_status_enum"),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "REJECTED",
                name="experience_verification_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"], ["destinations.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["provider_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiences_destination_id"),
        "experiences",
        ["destination_id"],
        unique=False,
    )
    op.create_index(op.f("ix_experiences_id"), "experiences", ["id"], unique=False)
    op.create_index(
        op.f("ix_experiences_provider_id"), "experiences", ["provider_id"], unique=False
    )
    op.create_index(op.f("ix_experiences_slug"), "experiences", ["slug"], unique=True)
    op.create_index(
        op.f("ix_experiences_status"), "experiences", ["status"], unique=False
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "TRAVELER",
                "HOST",
                "GUIDE",
                "EXPERIENCE_PROVIDER",
                "SERVICE_PROVIDER",
                name="role_enum",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role", name="uq_user_role"),
    )
    op.create_index(op.f("ix_user_roles_id"), "user_roles", ["id"], unique=False)
    op.create_index(op.f("ix_user_roles_role"), "user_roles", ["role"], unique=False)
    op.create_index(
        op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False
    )
    op.create_table(
        "experience_availabilities",
        sa.Column("experience_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("price_override", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["experience_id"], ["experiences.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "experience_id", "date", "start_time", name="uq_experience_date_time"
        ),
    )
    op.create_index(
        op.f("ix_experience_availabilities_date"),
        "experience_availabilities",
        ["date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experience_availabilities_experience_id"),
        "experience_availabilities",
        ["experience_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experience_availabilities_id"),
        "experience_availabilities",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experience_availabilities_is_available"),
        "experience_availabilities",
        ["is_available"],
        unique=False,
    )
    op.create_table(
        "experience_category_links",
        sa.Column("experience_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["experience_categories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["experience_id"], ["experiences.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "experience_id", "category_id", name="uq_experience_category"
        ),
    )
    op.create_index(
        op.f("ix_experience_category_links_category_id"),
        "experience_category_links",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experience_category_links_experience_id"),
        "experience_category_links",
        ["experience_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experience_category_links_id"),
        "experience_category_links",
        ["id"],
        unique=False,
    )
    op.create_table(
        "experience_images",
        sa.Column("experience_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["experience_id"], ["experiences.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experience_images_experience_id"),
        "experience_images",
        ["experience_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experience_images_id"), "experience_images", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_experience_images_id"), table_name="experience_images")
    op.drop_index(
        op.f("ix_experience_images_experience_id"), table_name="experience_images"
    )
    op.drop_table("experience_images")
    op.drop_index(
        op.f("ix_experience_category_links_id"), table_name="experience_category_links"
    )
    op.drop_index(
        op.f("ix_experience_category_links_experience_id"),
        table_name="experience_category_links",
    )
    op.drop_index(
        op.f("ix_experience_category_links_category_id"),
        table_name="experience_category_links",
    )
    op.drop_table("experience_category_links")
    op.drop_index(
        op.f("ix_experience_availabilities_is_available"),
        table_name="experience_availabilities",
    )
    op.drop_index(
        op.f("ix_experience_availabilities_id"), table_name="experience_availabilities"
    )
    op.drop_index(
        op.f("ix_experience_availabilities_experience_id"),
        table_name="experience_availabilities",
    )
    op.drop_index(
        op.f("ix_experience_availabilities_date"),
        table_name="experience_availabilities",
    )
    op.drop_table("experience_availabilities")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_experiences_status"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_slug"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_provider_id"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_id"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_destination_id"), table_name="experiences")
    op.drop_table("experiences")
    op.drop_index(
        op.f("ix_experience_categories_slug"), table_name="experience_categories"
    )
    op.drop_index(
        op.f("ix_experience_categories_name"), table_name="experience_categories"
    )
    op.drop_index(
        op.f("ix_experience_categories_id"), table_name="experience_categories"
    )
    op.drop_table("experience_categories")
    # ### end Alembic commands ###
